export const statsData = [
    {
        title: "Total Buildings",
        value: "3",
        iconType: "buildings",
        iconColor: "text-primary",
        iconBg: "bg-primary/10",
        url: "/buildings",
    },
    {
        title: "Total Apartments",
        value: "19",
        iconType: "apartments",
        iconColor: "text-dark-gray",
        iconBg: "bg-muted",
        url: "/apartments",
    },
    {
        title: "Occupied",
        value: "4",
        iconType: "tenants",
        iconColor: "text-accent",
        iconBg: "bg-accent/10",
        url: "/tenants",
    },
    {
        title: "Vacant",
        value: "2",
        iconType: "apartments",
        iconColor: "text-progress-tag-text",
        iconBg: "bg-progress-tag-bg",
        url: "/apartments",
    },
    {
        title: "Monthly Income",
        value: "₹130,000",
        iconType: "income",
        iconColor: "text-success-tag-text",
        iconBg: "bg-success-tag-bg",
        url: "/income",
    },
    {
        title: "Monthly Expense",
        value: "₹130,000",
        iconType: "expenses",
        iconColor: "text-destructive",
        iconBg: "bg-destructive/10",
        url: "/expenses",
    },
    {
        title: "Pending Payments",
        value: "4",
        iconType: "alert",
        iconColor: "text-progress-tag-text",
        iconBg: "bg-progress-tag-bg",
        url: "/income",
    },
    {
        title: "Open Maintenance",
        value: "2",
        iconType: "maintenance",
        iconColor: "text-dark-gray",
        iconBg: "bg-muted",
        url: "/maintenance",
    },
]
